services:
  mu_events:
    image: mu_events 
    build:
      context: NetApiPostgreSQL/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
  mu_events_db:
    image: mu_events_db
    build:
      context: postgreSQL/
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: webUser
      POSTGRES_PASSWORD: 159753
      POSTGRES_DB: mu_events_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  pgadmin_data: